### ISSUE TITLE
Page 并没有使用 Tina 的 .define

### ISSUE THREAD

**Issue by Yexiaoxing** [tinajs/template-mina#2]
https://github.com/tinajs/template-mina/blob/master/template/src/pages/home.mina#L67

用的还是 MINA 的 Page 定义，而不是 Tina 的 define。

**Comment by imyelo** [comment]
是的，因为 mina-webpack 和 tina 可以分别独立使用，脚手架 template-mina 生成的项目只包含了 mina-webpack 的部分。

如果希望搭配使用的话可以直接用 https://github.com/tinajs/template-tina 代替

**Comment by Yexiaoxing** [comment]
了解，看来是我理解错文档了。
